// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  const isNewKey = isNewSupabaseApiKey(supabaseKey);
  return (input, init) => {
    const headers = new Headers();

    // 1. Copy headers from the Request object if one was provided
    if (typeof Request !== 'undefined' && input instanceof Request) {
      input.headers.forEach((value, key) => headers.set(key, value));
    }

    // 2. Merge in any headers from init (these take precedence)
    if (init?.headers) {
      const initHeaders = init.headers instanceof Headers
        ? init.headers
        : new Headers(init.headers as HeadersInit);
      initHeaders.forEach((value, key) => headers.set(key, value));
    }

    // 3. For new opaque API keys, never send the key itself as a Bearer token.
    //    The key must only go in the `apikey` header.
    if (isNewKey) {
      const auth = headers.get('Authorization');
      if (auth === `Bearer ${supabaseKey}`) {
        headers.delete('Authorization');
      }
    }

    // 4. Always ensure apikey header is present
    if (!headers.has('apikey')) {
      headers.set('apikey', supabaseKey);
    }

    return fetch(input, { ...init, headers });
  };
}

function createSupabaseClient() {
  const SUPABASE_URL =
    import.meta.env.VITE_SUPABASE_URL ||
    import.meta.env.SUPABASE_URL ||
    (typeof process !== 'undefined' ? process.env?.VITE_SUPABASE_URL || process.env?.SUPABASE_URL : undefined) ||
    "https://xnkmnhyionnldgvaiprj.supabase.co";

  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
    import.meta.env.VITE_SUPABASE_ANON_KEY ||
    import.meta.env.SUPABASE_PUBLISHABLE_KEY ||
    import.meta.env.SUPABASE_ANON_KEY ||
    (typeof process !== 'undefined'
      ? process.env?.VITE_SUPABASE_PUBLISHABLE_KEY ||
        process.env?.VITE_SUPABASE_ANON_KEY ||
        process.env?.SUPABASE_PUBLISHABLE_KEY ||
        process.env?.SUPABASE_ANON_KEY
      : undefined) ||
    "sb_publishable_xVFb2j9WqShVlzDhfYPzbA_25ijOqLt";

  const customFetch = createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY);

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: customFetch,
      headers: {
        // For new-format keys, set the apikey header explicitly.
        // This ensures it's always present in auth client headers too.
        apikey: SUPABASE_PUBLISHABLE_KEY,
      },
    },
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

